CC = gcc
LDLIBS = -I/usr/local/include \
	 -L/usr/local/lib \
	 -lglut  -lGLU -lGL 

all: BackColor CoordSystem DrawLine DrawPoint DrawTriangle DrawQuad \
	DrawPoly DrawingObj Icosahedron MagicBox MoonSys MultObjTrans ObjectColor \
	OrderTrans1 OrderTrans2 PlanetSys PushPop RotTrans RotTrans2 Rotate Scale \
	SingleBuffer SpecMatrix Translate TriangulateEx WinPosition WinSize WinTitle \
	AntiPoly AntiRGB BlendExample TDBlending FogExample \
	Shading1 Shading2 \
	AmbLight DiffLight HidSurRem Lighting MatAmbience MatDiffuse MatShine LightSource \
	MoveLight MoveLightView SpecLight StatLight MatEmiss MatSpec SpotLight \
	FrustumIntro OrthoProjection PersProjection Viewport

BackColor:	BackColor.c
	$(CC) $@.c $(LDLIBS) -o $@
CoordSystem:	CoordSystem.c
	$(CC) $@.c $(LDLIBS) -o $@
DrawLine:	DrawLine.c
	$(CC) $@.c $(LDLIBS) -o $@
DrawPoint:	DrawPoint.c
	$(CC) $@.c $(LDLIBS) -o $@
DrawTriangle:	DrawTriangle.c
	$(CC) $@.c $(LDLIBS) -o $@
DrawQuad:	DrawQuad.c
	$(CC) $@.c $(LDLIBS) -o $@
DrawPoly:	DrawPoly.c
	$(CC) $@.c $(LDLIBS) -o $@
MultObjTrans:	MultObjTrans.c
	$(CC) $@.c $(LDLIBS) -o $@
ObjectColor:	ObjectColor.c
	$(CC) $@.c $(LDLIBS) -o $@
OrderTrans1:	OrderTrans1.c
	$(CC) $@.c $(LDLIBS) -o $@
OrderTrans2:	OrderTrans2.c
	$(CC) $@.c $(LDLIBS) -o $@
PushPop:	PushPop.c
	$(CC) $@.c $(LDLIBS) -o $@
RotTrans:	RotTrans.c
	$(CC) $@.c $(LDLIBS) -o $@
Rotate:	Rotate.c
	$(CC) $@.c $(LDLIBS) -o $@
Scale:	Scale.c
	$(CC) $@.c $(LDLIBS) -o $@
SpecMatrix:	SpecMatrix.c
	$(CC) $@.c $(LDLIBS) -o $@
Translate:	Translate.c
	$(CC) $@.c $(LDLIBS) -o $@
TriangulateEx:	TriangulateEx.c
	$(CC) $@.c $(LDLIBS) -o $@
WinPosition:	WinPosition.c
	$(CC) $@.c $(LDLIBS) -o $@
WinSize:	WinSize.c
	$(CC) $@.c $(LDLIBS) -o $@
WinTitle:	WinTitle.c
	$(CC) $@.c $(LDLIBS) -o $@
Shading1:	Shading1.c
	$(CC) $@.c $(LDLIBS) -o $@
Shading2:	Shading2.c
	$(CC) $@.c $(LDLIBS) -o $@
AntiPoly:	AntiPoly.c
	$(CC) $@.c $(LDLIBS) -o $@
AntiRGB: 	AntiRGB.c
	$(CC) $@.c $(LDLIBS) -o $@
AmbLight:	AmbLight.c
	$(CC) $@.c $(LDLIBS) -o $@
DiffLight:	DiffLight.c
	$(CC) $@.c $(LDLIBS) -o $@
HidSurRem:	HidSurRem.c
	$(CC) $@.c $(LDLIBS) -o $@
Lighting:	Lighting.c
	$(CC) $@.c $(LDLIBS) -o $@
MatAmbience:	MatAmbience.c
	$(CC) $@.c $(LDLIBS) -o $@
MatDiffuse:	MatDiffuse.c
	$(CC) $@.c $(LDLIBS) -o $@
MatEmiss:	MatEmiss.c
	$(CC) $@.c $(LDLIBS) -o $@
MatShine:	MatShine.c
	$(CC) $@.c $(LDLIBS) -o $@
MatSpec:	MatSpec.c
	$(CC) $@.c $(LDLIBS) -o $@
SpotLight:	SpotLight.c
	$(CC) $@.c $(LDLIBS) -o $@
LightSource:	LightSource.c
	$(CC) $@.c $(LDLIBS) -o $@
MoveLight:	MoveLight.c
	$(CC) $@.c $(LDLIBS) -o $@
MoveLightView:	MoveLightView.c
	$(CC) $@.c $(LDLIBS) -o $@
SpecLight:	SpecLight.c
	$(CC) $@.c $(LDLIBS) -o $@
StatLight:	StatLight.c
	$(CC) $@.c $(LDLIBS) -o $@
BlendExample:	BlendExample.c
	$(CC) $@.c $(LDLIBS) -o $@
TDBlending:	TDBlending.c
	$(CC) $@.c $(LDLIBS) -o $@
FogExample:	FogExample.c
	$(CC) $@.c $(LDLIBS) -o $@
FrustumIntro:	FrustumIntro.c
	$(CC) $@.c $(LDLIBS) -o $@
OrthoProjection:	OrthoProjection.c
	$(CC) $@.c $(LDLIBS) -o $@
PersProjection:	PersProjection.c
	$(CC) $@.c $(LDLIBS) -o $@
Viewport:	Viewport.c
	$(CC) $@.c $(LDLIBS) -o $@



