#!/bin/sh
# "kepupdate" is a simple shell script designed to update PREDICT's
# orbital database via the internet using the HTTP protocol.  It is
# designed to be placed in your home directory under a subdirectory
# called "cronjobs".  See the README file for more information.
#
wget -qc www.celestrak.com/NORAD/elements/amateur.txt -O $HOME/cronjobs/amateur.txt
wget -qc www.celestrak.com/NORAD/elements/visual.txt -O $HOME/cronjobs/visual.txt
wget -qc www.celestrak.com/NORAD/elements/weather.txt $HOME/cronjobs/weather.txt
/usr/local/bin/predict -u $HOME/cronjobs/amateur.txt
/usr/local/bin/predict -u $HOME/cronjobs/visual.txt
/usr/local/bin/predict -u $HOME/cronjobs/weather.txt
/usr/local/bin/kep_reload localhost
